name: flutter_repo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 页面手动切换
  flutter_swiper: ^1.1.6
  # 扫描二维码 条形码
  barcode_scan: ^1.0.0
  # 数据异步加载
  dio: ^2.1.3
  # 内嵌浏览器
  flutter_webview_plugin: ^0.3.5
  # 打电话 发短信 发邮件  跳网页
  url_launcher: ^5.0.2
  # html渲染
  flutter_html: ^0.9.6
  # 动态加载
  flutter_spinkit: "^3.1.0"
  # 条形码
  barcode_flutter: ^1.0.1
  # 二维码
  qr_flutter: ^2.0.0+51

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/guide.png
    - assets/images/guide_logo.png
    - assets/images/guide_logo_iphonex.png
    - assets/images/saoyisao.png
    - assets/images/bangka.png
    - assets/images/huiyuan.png
    - assets/images/jiaofei.png
    - assets/images/piaoquan.png
    - assets/images/index_pic.png
    - assets/images/index_pic2.png
    - assets/images/index_pic3.png
    - assets/images/index_pic4.png
    - assets/images/index_pic5.png
    - assets/images/index_pic6.png
    - assets/images/index_pic7.png
    - assets/images/index_pic8.png
    - assets/images/index_pic9.png
    - assets/images/index_pic10.png
    - assets/images/index_pic11.png
    - assets/images/index_pic12.png
    - assets/images/index_pic13.png
    - assets/images/index_pic14.png
    - assets/images/index_pic16.png
    - assets/images/index_pic17.png
    - assets/images/index_pic18.png
    - assets/images/index_pic19.png
    - assets/images/index_pic21.png
    - assets/images/index_pic22.png
    - assets/images/index_pic23.png
    - assets/images/index_pic24.png
    - assets/images/index_pic25.png
    - assets/images/index_pic26.png
    - assets/images/index_pic27.png
    - assets/images/index_pic28.png
    - assets/images/index_pic29.png
    - assets/images/index_pic30.png
    - assets/images/index_pic31.png
    - assets/images/tm.png
    - assets/images/myCard.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
